spring:
  primary:
    datasource:
      password: write
      username: fable_write
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres
  replica:
    datasource:
      password: read
      username: fable_read
      driver: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/postgres

  # Spring Boot 2 + Hibernate Issue: https://hibernate.atlassian.net/browse/HHH-12368
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  zipkin:
    locator:
      discovery:
        enabled: false
    enabled: true
    base-url: http://localhost:9411
    compression:
      enabled: false
    sender:
      type: web
    message-timeout: 5
  sleuth:
    sampler:
      percentage: 1
      
  cloud:
    inetutils:
      ignoredInterfaces:
        - docker0
        - veth.*
        - enp0s3
        - lo
      preferredNetworks:
        - 192.168.*.*
        - 172.21.1.*
#    stream:
#      default-binder: test
logging:
  file:
    mylog.log
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    sh.fable: DEBUG
    
# Register P6LogFactory to log JDBC events
decorator:
  datasource:
    p6spy:
      enable-logging: false
      multiline:  true   # Use com.p6spy.engine.spy.appender.MultiLineFormat instead of com.p6spy.engine.spy.appender.SingleLineFormat
      logging:   slf4j # Use logging for default listeners [slf4j, sysout, file]
      log-file:  spy.log # Log file to use (only with logging=file)
      # log-format:          # Custom log format, if specified com.p6spy.engine.spy.appender.CustomLineFormat will be used with this log format 
server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types:
    - application/json
    - application/xml
    - text/html
    - text/xml
    - text/plain
    - application/javascript
    - text/css